export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const FETCH_COUNTRY_INDICATOR = 'FETCH_COUNTRY_INDICATOR';
export const FETCH_COUNTRY_INDICATOR_SUCCESS = 'FETCH_COUNTRY_INDICATOR_SUCCESS';
export const FETCH_COUNTRY_INDICATOR_FAILURE = 'FETCH_COUNTRY_INDICATOR_FAILURE';
export const FETCH_COUNTRIES_LIST = 'FETCH_COUNTRIES_LIST';
export const FETCH_COUNTRIES_LIST_SUCCESS = 'FETCH_COUNTRIES_LIST_SUCCESS';
export const FETCH_COUNTRIES_LIST_FAILURE = 'FETCH_COUNTRIES_LIST_FAILURE';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const FETCH_COUNTRY_INDICATORS_FAILURE = 'FETCH_COUNTRY_INDICATORS_FAILURE';

export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
